import { cx } from "./utils";

const tones: Record<string, string> = {
  active: "success",
  available: "success",
  approved: "success",
  reviewed: "success",
  completed: "success",
  confirmed: "success",
  invoiced: "success",
  stocked: "success",
  online: "success",
  generated: "success",
  ready: "success",
  configured: "success",
  issued: "success",
  released: "success",
  red_issued: "success",
  passed: "success",
  ok: "success",
  sampling: "warning",
  testing: "warning",
  pending_review: "warning",
  event_only: "warning",
  delivering: "primary",
  dispatching: "primary",
  in_transit: "primary",
  assigned: "primary",
  arrived_site: "primary",
  loading: "primary",
  loaded: "primary",
  departed: "primary",
  arrived: "primary",
  arrived_project: "primary",
  unloading: "primary",
  returning: "primary",
  scheduled: "primary",
  producing: "primary",
  running: "primary",
  produced: "primary",
  submitting: "primary",
  submitted: "warning",
  accepted: "warning",
  red_offset: "warning",
  red_pending: "warning",
  credited: "warning",
  pending_approval: "warning",
  partial: "warning",
  warning: "warning",
  overbooked: "danger",
  no_capacity: "danger",
  shortage: "danger",
  missing: "danger",
  missing_trigger: "danger",
  missing_result_handler: "danger",
  unknown: "default",
  unconfigured: "warning",
  "local-simulator": "warning",
  registered: "warning",
  not_connected: "default",
  open: "warning",
  offline: "default",
  retired: "default",
  disabled: "default",
  cancelled: "danger",
  rejected: "danger",
  error: "danger",
  abnormal: "danger",
  failed: "danger",
  blocked: "danger",
  high: "danger"
};

const labels: Record<string, string> = {
  active: "启用",
  available: "可用",
  approved: "已审批",
  reviewed: "已复核",
  completed: "已完成",
  confirmed: "已确认",
  invoiced: "已开票",
  stocked: "已入库",
  generated: "已生成",
  ready: "已接入",
  configured: "已配置",
  issued: "蓝票",
  released: "已放行",
  red_issued: "红票已开",
  passed: "合格",
  ok: "正常",
  sampling: "抽样中",
  testing: "试验中",
  pending_review: "待复核",
  event_only: "仅事件",
  failed: "不合格",
  blocked: "冻结",
  online: "在线",
  offline: "离线",
  retired: "已停用",
  disabled: "已禁用",
  delivering: "发货中",
  dispatching: "调度中",
  in_transit: "运输中",
  assigned: "已派车",
  scheduled: "已排产",
  producing: "生产中",
  running: "执行中",
  produced: "已生产",
  submitting: "提交中",
  submitted: "已提交",
  accepted: "已受理",
  red_offset: "已红冲",
  red_pending: "红冲中",
  credited: "已冲抵",
  pending_approval: "待审批",
  partial: "部分实现",
  draft: "草稿",
  open: "待处理",
  warning: "预警",
  waiting_load: "等待装料",
  idle: "空闲",
  arrived_site: "已到厂",
  loading: "装料中",
  loaded: "已装料",
  departed: "已出厂",
  arrived: "已到场",
  arrived_project: "已到工地",
  unloading: "卸料中",
  returning: "返程中",
  signed: "已签收",
  valid: "有效",
  pending: "待处理",
  rejected: "已驳回",
  high: "高级",
  medium: "中级",
  low: "低级",
  overbooked: "超产能",
  no_capacity: "无产能",
  shortage: "库存不足",
  missing: "缺失",
  missing_trigger: "缺触发",
  missing_result_handler: "缺回写",
  unknown: "未知",
  unconfigured: "未配置",
  "local-simulator": "本地模拟",
  registered: "已登记",
  not_connected: "未接入",
  error: "异常"
};

export function statusLabel(value?: string) {
  const key = value || "default";
  return labels[key] || key;
}

export type StatusChipProps = {
  value?: string;
};

export function StatusChip({ value }: StatusChipProps) {
  const key = value || "default";
  return (
    <span className={cx("status-chip", tones[key] || "default")}>
      {statusLabel(key)}
    </span>
  );
}
