import { cn } from "@heroui/react";

const tones: Record<string, string> = {
  active: "success",
  available: "success",
  approved: "success",
  reviewed: "success",
  completed: "success",
  confirmed: "success",
  stocked: "success",
  online: "success",
  generated: "success",
  issued: "success",
  released: "success",
  red_issued: "success",
  passed: "success",
  sampling: "warning",
  testing: "warning",
  pending_review: "warning",
  delivering: "primary",
  dispatching: "primary",
  in_transit: "primary",
  assigned: "primary",
  arrived_site: "primary",
  loading: "primary",
  loaded: "primary",
  departed: "primary",
  arrived: "primary",
  arrived_project: "primary",
  unloading: "primary",
  returning: "primary",
  scheduled: "primary",
  producing: "primary",
  running: "primary",
  produced: "primary",
  submitting: "primary",
  submitted: "warning",
  accepted: "warning",
  red_offset: "warning",
  red_pending: "warning",
  credited: "warning",
  pending_approval: "warning",
  partial: "warning",
  warning: "warning",
  open: "warning",
  offline: "default",
  retired: "default",
  disabled: "default",
  cancelled: "danger",
  rejected: "danger",
  abnormal: "danger",
  failed: "danger",
  blocked: "danger",
  high: "danger"
};

const labels: Record<string, string> = {
  active: "启用",
  available: "可用",
  approved: "已审批",
  reviewed: "已复核",
  completed: "已完成",
  confirmed: "已确认",
  stocked: "已入库",
  generated: "已生成",
  issued: "蓝票",
  released: "已放行",
  red_issued: "红票已开",
  passed: "合格",
  sampling: "抽样中",
  testing: "试验中",
  pending_review: "待复核",
  failed: "不合格",
  blocked: "冻结",
  online: "在线",
  offline: "离线",
  retired: "已停用",
  disabled: "已禁用",
  delivering: "发货中",
  dispatching: "调度中",
  in_transit: "运输中",
  assigned: "已派车",
  scheduled: "已排产",
  producing: "生产中",
  running: "执行中",
  produced: "已生产",
  submitting: "提交中",
  submitted: "已提交",
  accepted: "已受理",
  red_offset: "已红冲",
  red_pending: "红冲中",
  credited: "已冲抵",
  pending_approval: "待审批",
  partial: "部分实现",
  draft: "草稿",
  open: "待处理",
  warning: "预警",
  waiting_load: "等待装料",
  idle: "空闲",
  arrived_site: "已到厂",
  loading: "装料中",
  loaded: "已装料",
  departed: "已出厂",
  arrived: "已到场",
  arrived_project: "已到工地",
  unloading: "卸料中",
  returning: "返程中",
  signed: "已签收",
  valid: "有效",
  pending: "待处理",
  rejected: "已驳回",
  high: "高级",
  medium: "中级",
  low: "低级"
};

export function StatusChip({ value }: { value?: string }) {
  const key = value || "default";
  return (
    <span className={cn("status-chip", tones[key] || "default")}>
      {labels[key] || key}
    </span>
  );
}
